version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  test:
    desc: Run all Go tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint checks
    cmds:
      - golangci-lint run

  fmt:
    desc: Format Go source files using golangci-lint
    cmds:
      - golangci-lint run --fix --disable-all --enable gofmt

  build:
    desc: Build the envault CLI
    cmds:
      - go build ./cmd/envault

  ci:
    desc: Run local checks aligned with CI
    cmds:
      - task: fmt
      - task: lint
      - task: test
