version: "3"

env:
  GOCACHE: "{{.TASKFILE_DIR}}/.cache/go-build"
  GOLANGCI_LINT_CACHE: "{{.TASKFILE_DIR}}/.cache/golangci-lint"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  test:
    desc: Run all Go tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint checks
    cmds:
      - golangci-lint run

  fmt:
    desc: Format Go source files using golangci-lint
    cmds:
      - golangci-lint fmt

  build:
    desc: Build the envchain CLI
    cmds:
      - go build ./cmd/envchain

  ci:
    desc: Run local checks aligned with CI
    cmds:
      - task: fmt
      - task: lint
      - task: test
